"""Harvesting confirmed values into training data (step.md step 3r.6c,
plan.md §16 "Harvesting labels from real use"). The review screen (step
7) is already a labelling machine: every digit the instructor confirms or
corrects is a labelled crop of exactly the handwriting that matters,
including student handwriting that could never be collected in advance.

Built now even though nothing consumes it yet — no fine-tuning exists to
train on these labels. Retrofitting this later would mean losing every
label from the pilot, which is the period these labels matter most
(plan.md §16's own reasoning for building this ahead of need).

Tags corrections separately from confirmations: corrections are the
model's actual failures and worth oversampling; confirmations mostly
re-teach what it already knows. A field the original scan flagged (None,
low-confidence) that the instructor then filled in counts as a correction
too — the model failed to produce a usable answer there, the same as if
it had produced a wrong one.

Where the crops physically land is `stores.py`'s problem, not this
module's (step 11.2). This file decides the *label* — the field, the tag,
and the value — and hands a key to a Store. That split is what lets the
same code write to a laptop directory and to S3 with a byte-identical
layout, so the fine-tuning code never has to know which was used.
"""
from __future__ import annotations

import hashlib
import random
import re
from pathlib import Path

from .marks import _fmt
from .stores import Store

# A harvest request that carries no source tag is filed under this prefix
# rather than being given one invented server-side. One shared backend
# serves every faculty member, so a server-generated tag would label them
# all identically and destroy the only thing the tag is for. A missing tag
# should be visible in the bucket, not silently papered over (11.2.5).
UNKNOWN_SOURCE = "unknown"

# Reserved prefix for anything generated while verifying the system rather
# than while grading a real class. `fetch-crops.sh` filters these out of the
# training set by default.
#
# This exists because the alternative failed: verification runs previously
# wrote into the same namespace as real collection, and separating them
# afterwards was impossible — the corpus had to be thrown away. A structural
# separation cannot be forgotten the way a convention can.
TEST_SOURCE_PREFIX = "test-"


def _sanitize_source(source: str | None) -> str:
    """The source id becomes a path/key segment, so it is never
    interpolated raw. It is generated by `crypto.randomUUID()` on the
    client, but `/api/harvest` is a public endpoint and this arrives in a
    form field — a `../..` here would otherwise escape the harvest root."""
    if not source:
        return UNKNOWN_SOURCE
    cleaned = "".join(c for c in source if c.isalnum() or c in "-_")
    return cleaned or UNKNOWN_SOURCE


# The label a crop is filed under, as a SHAPE rather than an alphabet.
#
# An alphabet was the first attempt (`^[0-9.?]{1,8}$`) and it was too loose:
# ".." matches it, because "." has to be legal for a half mark. That one is
# inert — `_key` renders it as the filename `.._<digest>.png`, never a bare
# path segment — but it is still a nonsense label sitting in the training
# corpus, and "inert today" is a bad thing to rely on when the value is
# attacker-supplied. Caught by a parametrised test, not by inspection.
#
# So: exactly one of the three things a label can actually be.
#   "?"        one deliberately-unreadable position
#   "07"       a serial, as written, leading zero preserved
#   "4" "2.5"  a mark, `_fmt`-formatted (at most one decimal place)
_SAFE_VALUE = re.compile(r"^(\?|[0-9]{1,4}(\.[0-9]{1,2})?)$")


def _sanitize_value(value: str) -> str | None:
    """Returns the value if it is safe to put in a path, else None.

    **This is the fix for issues.md N1, and the reasoning above
    `_sanitize_source` is exactly why it has to exist.** That docstring
    correctly identified `/api/harvest` as a public endpoint whose form
    fields reach a filesystem path — and then guarded one field. `value`,
    interpolated by `_key` one line along, was not guarded, so a
    `confirmed.serial` of `"../../../../escaped/PWNED"` wrote a PNG outside
    the harvest root. Verified by running it, not by reading it.

    An allow-list rather than a denylist, and a rejection rather than a
    scrub: a value that is not a legal label is not a label at all, so
    filing it under some cleaned-up approximation would put a wrong label
    on a real crop — which is worse for the training corpus than dropping
    it. Dropping is also what the rest of this module already does with a
    field it cannot use.
    """
    return value if _SAFE_VALUE.match(value) else None


def _key(field: str, tag: str, value: str, source: str, crop_path: Path) -> str:
    """The label lives in the filename — the same self-labelling principle
    the collection sheet (step 3r.6a) uses, so no separate annotation file
    has to stay in sync with the images.

    The suffix is a hash of the crop's own bytes rather than a uuid4, which
    makes writes **idempotent**: re-confirming the same script produces the
    same key and overwrites instead of accumulating a near-duplicate. That
    matters because it is exactly how the corpus got poisoned the first
    time — a step 6/7 phone-testing session re-photographed the same two
    scripts dozens of times, and every Confirm harvested again, leaving a
    digit histogram that reflected one student ID rather than handwriting.

    It keeps the unlinkability a uuid4 gave: two different digits from one
    student hash differently, so nothing groups a student's crops together
    (see also `_write_unordered` and stores.py's CONSTANT_MTIME).

    One accepted trade: a content-addressed store lets someone holding a
    candidate crop test whether it is in the corpus. For a pile of
    anonymous single digits that is a far smaller problem than the
    duplication it prevents.
    """
    digest = hashlib.sha256(crop_path.read_bytes()).hexdigest()[:32]
    return f"{source}/{field}/{tag}/{value}_{digest}.png"


def _write_unordered(pending: list[tuple[str, Path]], store: Store) -> None:
    """Writes crops in a random order, NOT the order they were collected.

    This is the third leg of the same privacy property as stores.py's
    CONSTANT_MTIME, and it exists because that one does not survive S3.
    The digits of one student's ID are collected in ID order; a store that
    records *when* each object arrived therefore re-sorts them back into
    that order, and the random filenames do nothing to prevent it.

    On the local filesystem `CONSTANT_MTIME` erases that signal after the
    fact. On S3 it cannot: `LastModified` is stamped server-side, at
    millisecond precision, and is not settable. Measured against a real S3
    API before this was added — sorting one harvest's ID crops by
    LastModified reproduced the student ID exactly, digit for digit.

    So the ordering is destroyed at the source instead, which works on any
    backend including ones not written yet. What remains visible is the
    burst itself (n crops arriving together) and the multiset of labels —
    both inherent to storing labelled crops at all, and neither of which
    reconstructs an ID.
    """
    random.shuffle(pending)
    for key, crop_path in pending:
        store.put(key, crop_path)


def harvest(
    cells_dir: Path,
    id_digits: int,
    question_count: int,
    original_student_id: str | None,
    confirmed_student_id: str | None,
    original_serial: str | None,
    confirmed_serial: str | None,
    original_questions: list[float | None],
    confirmed_questions: list[float | None],
    original_total: float | None,
    confirmed_total: float | None,
    store: Store,
    source: str | None = None,
) -> None:
    """Writes each relevant cell crop to `store` under
    <source>/<field>/{confirmed,corrected}/<value>_<uuid>.png. Only fields
    the instructor actually confirmed with a real value are harvested — an
    empty confirmed field means it stayed blank on the review screen,
    which isn't a label of anything.

    `source` is a per-faculty tag (step 11.2.4) — NOT per-scan and NOT
    per-student. plan.md §16 needs to hold out an unseen writer to measure
    fine-tuning honestly, which is impossible once several faculty pool
    into one bucket with no way to tell them apart. Per-scan would be
    actively harmful: it would regroup one student's digits and undo
    11.0.2 outright."""
    src = _sanitize_source(source)

    # Collected first, written later and in a random order — see
    # _write_unordered. Nothing reaches the store until every field has
    # been decided.
    pending: list[tuple[str, Path]] = []

    def add(field: str, tag: str, value: str, crop_path: Path) -> None:
        # Sanitized HERE, in the one place every field funnels through, so
        # no field added later can forget it (issues.md N1). The previous
        # arrangement guarded `source` at the top of this function and left
        # `value` unguarded, which is precisely the failure a per-call-site
        # convention produces.
        safe = _sanitize_value(value)
        if safe is None:
            return
        if crop_path.exists():
            pending.append((_key(field, tag, safe, src, crop_path), crop_path))

    if confirmed_student_id:
        for i in range(1, id_digits + 1):
            if i - 1 >= len(confirmed_student_id):
                break
            confirmed_digit = confirmed_student_id[i - 1]
            original_digit = (
                original_student_id[i - 1]
                if original_student_id and i - 1 < len(original_student_id)
                else None
            )
            tag = "confirmed" if confirmed_digit == original_digit else "corrected"
            add("id_digits", tag, confirmed_digit, cells_dir / f"id_d{i}.png")

    if confirmed_serial:
        tag = "confirmed" if confirmed_serial == original_serial else "corrected"
        add("serial", tag, confirmed_serial, cells_dir / "serial.png")

    for i in range(question_count):
        confirmed_value = confirmed_questions[i] if i < len(confirmed_questions) else None
        if confirmed_value is None:
            continue
        original_value = original_questions[i] if i < len(original_questions) else None
        tag = "confirmed" if confirmed_value == original_value else "corrected"
        add(f"marks_q{i + 1}", tag, _fmt(confirmed_value), cells_dir / f"marks_r1_c{i}.png")

    if confirmed_total is not None:
        tag = "confirmed" if confirmed_total == original_total else "corrected"
        add("marks_total", tag, _fmt(confirmed_total), cells_dir / f"marks_r1_c{question_count}.png")

    _write_unordered(pending, store)
